server:
  port: 8080

spring:
  application:
    name: 9900-project-test
  datasource:
    url: jdbc:sqlite:9900-test-db.sqlite?date_string_format=yyyy-MM-dd
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.desire.entity
logging:
  path: ./
  file: 9900-project.log
  level:
    unsw_9900.nobugs.mapper: debug
